name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CodeCoverage:

    runs-on: ubuntu-latest

    steps:
    - uses: aki77/simplecov-report-action@v1
    - name: Simplecov Report
