name: Code Coverage
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    steps:
      - name: Test
        run: rake test

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
