name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t cryptomanagement:v1 .

    - name: Execute code coverage
      run: docker run -i -v `pwd`:/testdir cryptomanagement:v1 rake coverage
